In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr * 2
print(result)

[2 4 6]


In [ ]:
import numpy as np

a = np.array([ 1, 2,3])
b = np .array([[10],[20],[30]])
print(a.shape)
print(b.shape)

c = a + b

print(c)


(3,)
(3, 1)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
import numpy as np

array1 = np.array([[1,2,3,4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

result = array1 * array2
print(result)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
import numpy as np

array1 = np.array([[1,2,3,4],[5,6,7,8]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

result = array1 * array2
print(result)

(2, 4)
(4, 1)


ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

In [ ]:
import numpy as np

array1 = np.array([[1,2,3,4], [5,6,7,8], [9,10, 11,12], [13,14, 15, 16]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

result = array1 * array2
print(result)

(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [ ]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

print(array1.shape)
print(array2.shape)

result = array1 + array2
print(result)

(2, 3)
(2, 1)
[[11 12 13]
 [24 25 26]]


In [ ]:
import numpy as np

array1 = np.array([[0,1,2]])
print(array1.shape)
array2 = np.array([[0],[1], [2]])
print(array2.shape)

result = array1 + array2
print(result)

(1, 3)
(3, 1)
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np

M = np.ones((3,3), dtype=float)
print(M)
a = np. array([1,2,3])

print(M.shape)
print(a.shape)

result = M + a

print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
(3,)
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
import numpy as np

M = np.ones((2,3))
a = np.arange(3)

print(M.shape)
print(a.shape)

result = M + a
print(result)

(2, 3)
(3,)
[[1. 2. 3.]
 [1. 2. 3.]]


In [ ]:
import numpy as np

arr1 = np.arange(3).reshape((3,1))
arr2 = np.arange(3)

print(arr1.shape)
print(arr2.shape)

result = arr1 + arr2
print(result)

(3, 1)
(3,)
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
arr2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(arr1.shape)
print(arr2.shape)

result = arr1 * arr2
print(result)


(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
import numpy as np

arr = np.array([ 1, 2, 3])
result = arr * 2
print(result)

[2 4 6]


In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])
print(a.shape)
print(b.shape)
result = a+b
print(result)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

ages = np.array([12, 24, 35, 45, 60, 72])

age_group = np.array(["Adult", "Minor"])

result = np.where(ages > 18, age_group[0], age_group[1])

print(result)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']
