https://numpy.org/doc/stable/user/basics.broadcasting.html


In [ ]:
import numpy as np

# arrays of same shape: (3,) x (3,) -> (3,)
print(np.array([1,2,3]) * np.array([4,5,6]))    

# array with scalar: () x (3,) -> (3,)
print(2 * np.array([1,2,3]))
# np.array(2) * np.array([1,2,3])    # equivalent: np.array(2) is also scalar, has shape ()

# 2 array dimensions are compatible if they are equal or one of them is 1 : (3,2) x (3,1) -> (3,2)
print(np.random.rand(3,2) * np.random.rand(3,1))

# arrays with different number of dimensions - greater no. of array dimensions are used in answer; missing dimensions treated as 1
# NOTE: this would have raised error if second 1D array had for example (4,) shape, 
# because then it won't line up with last axis of first array
print(np.random.rand(2,4,3) * np.array([1,2,3]))    # (2,4,3) x (3,) [ treated as (1,1,3) ] -> (2,4,3)

try:
    print(np.array([1,2]) * np.array([2,3,4]))      # mismatch shape raises ValueError
except ValueError as e:
    print(e)

# example: outer product (2D) of 2 1D arrays
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a[:, np.newaxis] + b)    # NOTE: in array slice, np.newaxis (equivalent to None) inserts new array dimension

[ 4 10 18]
[2 4 6]
[[0.39728872 0.51563835]
 [0.01548349 0.2272923 ]
 [0.13458279 0.13200777]]
[[[0.97835916 0.65753486 1.26447773]
  [0.97413254 1.9163723  2.61741499]
  [0.66173785 1.86912236 1.32781355]
  [0.84172885 1.39109191 1.41759575]]

 [[0.22381703 1.39850689 1.73385006]
  [0.70410694 0.58667611 1.34833845]
  [0.86938372 0.57954557 2.72807116]
  [0.0188298  1.17834381 1.98528712]]]
operands could not be broadcast together with shapes (2,) (3,) 
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
