Assignment 1 - Qns 3,4,7

Qn 3

In [1]:
import numpy as np

# --- Part a & b ---
print("--- Part a & b ---")
A = np.array([[1, -1, 2],
              [2,  2, 4],
              [3,  4, 6]], dtype=float)

det_A = np.linalg.det(A)
rank_A = np.linalg.matrix_rank(A)
print(f"Determinant of A: {det_A:.4f}")
print(f"Rank of A: {rank_A}")

try:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
except np.linalg.LinAlgError as e:
    print(f"Difficulty inverting matrix A: {e} (Determinant is 0)")


# --- Part c ---
print("\n--- Part c ---")
B = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]], dtype=float)

eigenvalues_B = np.linalg.eigvals(B)
m1 = B[0, 0]
m2 = np.linalg.det(B[:2, :2])
m3 = np.linalg.det(B)

print(f"Leading Principal Minors of B: M1={m1:.1f}, M2={m2:.1f}, M3={m3:.1f}")
print(f"Eigenvalues of B: {eigenvalues_B}")
print(f"Is B Positive Definite? {np.all(eigenvalues_B > 0)}")


# --- Part d ---
print("\n--- Part d ---")
C = np.array([[2, -2, -4],
              [-1, 3, 4],
              [1, -2, -3]], dtype=float)

C_squared = np.dot(C, C)
print("C^2 Matrix:\n", C_squared)
print(f"Is Matrix C Idempotent (C^2 == C)? {np.allclose(C_squared, C)}")


# --- Part e ---
print("\n--- Part e ---")
x = np.array([[0.2534, -0.9674],
              [0.9674, 0.2534]], dtype=float)

xx_t = np.dot(x, x.T)
dot_product_rows = np.dot(x[0], x[1])
norm_row1 = np.linalg.norm(x[0])
norm_row2 = np.linalg.norm(x[1])

print("x * x^T matrix:\n", xx_t)
print(f"Dot product of rows (Orthogonality check): {dot_product_rows:.4f}")
print(f"Norm of row 1: {norm_row1:.4f}, Norm of row 2: {norm_row2:.4f} (Orthonormality check)")
print(f"Is xx^T close to Identity matrix? {np.allclose(xx_t, np.eye(2), atol=1e-3)}")

--- Part a & b ---
Determinant of A: 0.0000
Rank of A: 2
Difficulty inverting matrix A: Singular matrix (Determinant is 0)

--- Part c ---
Leading Principal Minors of B: M1=2.0, M2=3.0, M3=4.0
Eigenvalues of B: [3.41421356 2.         0.58578644]
Is B Positive Definite? True

--- Part d ---
C^2 Matrix:
 [[ 2. -2. -4.]
 [-1.  3.  4.]
 [ 1. -2. -3.]]
Is Matrix C Idempotent (C^2 == C)? True

--- Part e ---
x * x^T matrix:
 [[ 1.00007432e+00 -6.05435702e-19]
 [-6.05435702e-19  1.00007432e+00]]
Dot product of rows (Orthogonality check): 0.0000
Norm of row 1: 1.0000, Norm of row 2: 1.0000 (Orthonormality check)
Is xx^T close to Identity matrix? True


Qn 4

In [2]:
import scipy.linalg as la

# Define the matrix A
A = np.array([[4, 12, -16],
              [12, 37, -43],
              [-16, -43, 98]], dtype=float)

print("=== PART A: Cholesky Decomposition ===")
try:
    L_cho = np.linalg.cholesky(A)
    print("Cholesky Factor L:\n", L_cho)
    print("\nVerification (L * L^T):\n", np.dot(L_cho, L_cho.T))
except np.linalg.LinAlgError:
    print("Matrix is not positive-definite or symmetric.")

print("\n=== PART B: LU Decomposition (Without Pivoting) ===")
# Custom Doolittle LU solver to avoid automatic row permutations for a direct match
def doolittle_lu(M):
    n = M.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            U[i, j] = M[i, j] - sum(L[i, k] * U[k, j] for k in range(i))
        for j in range(i + 1, n):
            L[j, i] = (M[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]
    return L, U

L_lu, U_lu = doolittle_lu(A)
print("LU Factor L:\n", L_lu)
print("\nLU Factor U:\n", U_lu)
print("\nVerification (L * U):\n", np.dot(L_lu, U_lu))

=== PART A: Cholesky Decomposition ===
Cholesky Factor L:
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]

Verification (L * L^T):
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]

=== PART B: LU Decomposition (Without Pivoting) ===
LU Factor L:
 [[ 1.  0.  0.]
 [ 3.  1.  0.]
 [-4.  5.  1.]]

LU Factor U:
 [[  4.  12. -16.]
 [  0.   1.   5.]
 [  0.   0.   9.]]

Verification (L * U):
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]


Qn 7

In [4]:
import pandas as pd

data = [10, 12, 11, 9, 9, 10, 11, 12, 11, 10, 11, 12]

# Descriptive summary calculations
mean_val = np.mean(data)
sample_var = np.var(data, ddof=1)
sample_std = np.std(data, ddof=1)

# Python options to cover different textbook quartile definitions
q1_inclusive = np.percentile(data, 25, method='hazen')      # Matches (n+1) interpolation
q3_inclusive = np.percentile(data, 75, method='hazen')

print(f"Mean: {mean_val:.4f}")
print(f"Sample Variance: {sample_var:.4f}")
print(f"Sample Standard Deviation: {sample_std:.4f}")
print(f"Median (Q2): {np.median(data):.1f}")
print(f"First Quartile (Q1 - Interpolated): {q1_inclusive:.2f}")
print(f"Third Quartile (Q3 - Interpolated): {q3_inclusive:.2f}")

Mean: 10.6667
Sample Variance: 1.1515
Sample Standard Deviation: 1.0731
Median (Q2): 11.0
First Quartile (Q1 - Interpolated): 10.00
Third Quartile (Q3 - Interpolated): 11.50
