# Import the libraries


In [ ]:
import numpy as np
np.set_printoptions(precision=2)
from scipy.linalg import fractional_matrix_power


# Milestone 1: Simple Matrix Operations

In [ ]:


print("--- 1. Simple Matrix Operations ---")
# Define a 3x2 matrix A
A = np.array([
    [1, 4],
    [2, 5],
    [3, 6]
])

# Get the order of the matrix (rows x columns)
sA = A.shape
print(f"Matrix A:\n{A}\nOrder of A: {sA}")

# Transpose of matrix A: rows become columns and columns become rows
B = A.T
sB = B.shape
print(f"\nTranspose of A (Matrix B):\n{B}\nOrder of B: {sB}")

# Matrix multiplication of A (3x2) and its transpose A' (2x3) resulting in a 3x3 matrix
C = A @ A.T
print(f"\nMatrix C (A * A'):\n{C}\nOrder of C: {C.shape}")

# Matrix multiplication of A' (2x3) and A (3x2) resulting in a symmetric 2x2 matrix
D = A.T @ A
print(f"\nMatrix D (A' * A, symmetric):\n{D}")
print("hello world")

--- 1. Simple Matrix Operations ---
Matrix A:
[[1 4]
 [2 5]
 [3 6]]
Order of A: (3, 2)

Transpose of A (Matrix B):
[[1 2 3]
 [4 5 6]]
Order of B: (2, 3)

Matrix C (A * A'):
[[17 22 27]
 [22 29 36]
 [27 36 45]]
Order of C: (3, 3)

Matrix D (A' * A, symmetric):
[[14 32]
 [32 77]]
hello world


# Milestone 2: Determinants and Inverses

In [ ]:

print("\n--- 2. Determinants and Inverses ---")

# Define a 2x2 square matrix M
M = np.array([
    [1, 2],
    [3, 4]
])

# The determinant of a 2x2 matrix [a b; c d] is ad - bc
DeterminantM = np.linalg.det(M)
print(f"Matrix M:\n{M}\nDeterminant of M: {DeterminantM:.2f}")

# The inverse of a matrix M, denoted as M^-1
InvM = np.linalg.inv(M)
print(f"Inverse of M (InvM):\n{InvM}")

# Multiplying a matrix by its inverse yields the Identity matrix (I)
Check = M @ InvM
print(f"Check M * InvM (Should be Identity Matrix):\n{np.round(Check, 4)}")



--- 2. Determinants and Inverses ---
Matrix M:
[[1 2]
 [3 4]]
Determinant of M: -2.0000
Inverse of M (InvM):
[[-2.   1. ]
 [ 1.5 -0.5]]
Check M * InvM (Should be Identity Matrix):
[[1. 0.]
 [0. 1.]]


# Milestone 3: Eigenvalues and Eigenvectors

In [ ]:

print("\n--- 3. Eigenvalues and Eigenvectors ---")

# Find the eigenvalues and eigenvectors of the square matrix D
# Eigenvectors represent directions that remain unchanged during the transformation
# Eigenvalues represent the scaling factor applied to those eigenvectors
eva, eve = np.linalg.eig(D)

print(f"Matrix D:\n{D}")
print(f"Eigenvalues of D:\n{eva}")
print(f"Eigenvectors of D:\n{eve}")




--- 3. Eigenvalues and Eigenvectors ---
Matrix D:
[[14 32]
 [32 77]]
Eigenvalues of D:
[ 0.6 90.4]
Eigenvectors of D:
[[-0.92 -0.39]
 [ 0.39 -0.92]]


# Milestone 4: Positive Definite Matrices (PDM)

In [ ]:

print("\n--- 4. Positive Definite Matrices (PDM) ---")

# A symmetric matrix is positive definite if all its eigenvalues are strictly positive
PDM = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])
print(f"Positive Definite Matrix (PDM):\n{PDM}")





--- 4. Positive Definite Matrices (PDM) ---
Positive Definite Matrix (PDM):
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


In [ ]:
# Verify eigenvalues are all > 0
evaPDM, evePDM = np.linalg.eig(PDM)
print(f"Eigenvalues of PDM (Notice all are > 0): {evaPDM}")



Eigenvalues of PDM (Notice all are > 0): [3.41 2.   0.59]


In [ ]:
# A positive definite matrix always has a positive determinant
determinant_PDM = np.linalg.det(PDM)
print(f"Determinant of PDM: {determinant_PDM:.2f}")



Determinant of PDM: 4.00


In [ ]:
# For any non-zero column vector u, the quadratic form u^T * PDM * u must be > 0
u = np.array([[-1], [-1], [-1]])
uTPDMu = u.T @ PDM @ u
print(f"Quadratic form u^T * PDM * u (Should be > 0): {uTPDMu[0][0]}")



Quadratic form u^T * PDM * u (Should be > 0): 2


In [ ]:
# Cholesky Decomposition: Decomposes a PDM into a lower triangular matrix (L) and its transpose (R)
print("\nCholesky Decomposition:")
L = np.linalg.cholesky(PDM)
R = L.T
print(f"Lower Triangular Factor (L):\n{L}")
print(f"Check L * L^T (Should equal PDM):\n{np.round(L @ L.T, 4)}")


Cholesky Decomposition:
Lower Triangular Factor (L):
[[ 1.41  0.    0.  ]
 [-0.71  1.22  0.  ]
 [ 0.   -0.82  1.15]]
Check L * L^T (Should equal PDM):
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


# Milestone 5: Orthogonal Matrices (OGM)

In [ ]:

print("\n--- 5. Orthogonal Matrices (OGM) ---")

# An orthogonal matrix has orthonormal rows/columns and its transpose equals its inverse
OGM1 = np.array([
    [1/np.sqrt(2), -1/np.sqrt(2)],
    [1/np.sqrt(2),  1/np.sqrt(2)]
])
print(f"Orthogonal Matrix 1 (OGM1):\n{OGM1}")




--- 5. Orthogonal Matrices (OGM) ---
Orthogonal Matrix 1 (OGM1):
[[ 0.71 -0.71]
 [ 0.71  0.71]]


In [ ]:
# For orthogonal matrices, OGM * OGM^T = I
IsitI = OGM1 @ OGM1.T
print(f"Check OGM1 * OGM1^T (Should be Identity):\n{np.round(IsitI, 4)}")
# The determinant of an orthogonal matrix is always +1 or -1
print(f"Determinant of OGM1: {np.linalg.det(OGM1):.2f}")


Check OGM1 * OGM1^T (Should be Identity):
[[ 1. -0.]
 [-0.  1.]]
Determinant of OGM1: 1.00


In [ ]:


# Orthogonal transformations preserve the length (magnitude) of vectors
a = np.array([-10, 20])
b = OGM1 @ a
print(f"\nLength Preservation:")
print(f"Length of original vector 'a': {np.linalg.norm(a):.2f}")
print(f"Length of transformed vector 'b' (OGM1 * a): {np.linalg.norm(b):.2f}")




Length Preservation:
Length of original vector 'a': 22.36
Length of transformed vector 'b' (OGM1 * a): 22.36


$$ \|\vec{c}_2 \times \vec{d}_2\| = \|\vec{c}_2\| \|\vec{d}_2\| \sin(\theta) $$
$$ \vec{c}_2 \cdot \vec{d}_2 = \|\vec{c}_2\| \|\vec{d}_2\| \cos(\theta) $$

$$ \theta_2 = \operatorname{arctan2}(\|\vec{c}_2 \times \vec{d}_2\|, \vec{c}_2 \cdot \vec{d}_2) $$


np.arctan2(y, x): The arctan2 function computes the inverse tangent of $y/x$. By passing the cross product magnitude as $y$ and the dot product as $x$, the vector magnitudes ($\|\vec{c}_2\| \|\vec{d}_2\|$) cancel out

$$ \frac{y}{x} = \frac{\|\vec{c}_2\| \|\vec{d}_2\| \sin(\theta)}{\|\vec{c}_2\| \|\vec{d}_2\| \cos(\theta)} = \frac{\sin(\theta)}{\cos(\theta)} = \tan(\theta) $$

In [ ]:
# Orthogonal transformations also preserve the angles between vectors
c = np.array([1, -4, 7])
d = np.array([-7, 2, 5])

# Calculate initial angle between vectors c and d
theta = np.arctan2(np.linalg.norm(np.cross(c, d)), np.dot(c, d))

# Define a 3x3 orthogonal matrix
OGM3 = np.array([
    [1/3,  2/3,  2/3],
    [2/3,  1/3, -2/3],
    [2/3, -2/3,  1/3]
])

# Apply the 3x3 orthogonal transformation to both vectors
c2 = OGM3 @ c
d2 = OGM3 @ d

# Calculate the angle between the newly transformed vectors
theta2 = np.arctan2(np.linalg.norm(np.cross(c2, d2)), np.dot(c2, d2))

print(f"\nAngle Preservation:")
print(f"Original angle between 'c' and 'd' (degrees): {np.degrees(theta):.2f}")
print(f"Transformed angle between 'c2' and 'd2' (degrees): {np.degrees(theta2):.2f}")


Angle Preservation:
Original angle between 'c' and 'd' (degrees): 73.81
Transformed angle between 'c2' and 'd2' (degrees): 73.81


# Milestone 6: Idempotent Matrix

In [ ]:

print("\n--- 6. Idempotent Matrix ---")
IMP1 = np.array([
    [1, 0, 0],
    [0, 1/2, 1/2],
    [0, 1/2, 1/2]
]).T
print("IMP1 =\n", IMP1)



--- 6. Idempotent Matrix ---
IMP1 =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
IMP2 = np.linalg.matrix_power(IMP1, 2)  # As shown below it is same as IMP1
print("\nIMP2 =\n", IMP2)





IMP2 =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
IMP3 = np.linalg.matrix_power(IMP1, 3)  # As shown below it is same as IMP1
print("\nIMP3 =\n", IMP3)






IMP3 =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
IMP10 = np.linalg.matrix_power(IMP1, 10)  # As shown below it is still same same as IMP1
print("\nIMP10 =\n", IMP10)






IMP10 =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
# Let us take square root of IMP1
IMP1_powerhalf = fractional_matrix_power(IMP1, 0.5)  # Still same what a matrix
print("\nIMP1_powerhalf =\n", IMP1_powerhalf)






IMP1_powerhalf =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
# Note np.sqrt(IMP1) is not equal to IMP1^0.5 (matrix power)
# One final try

IMP1_poweronethird = fractional_matrix_power(IMP1, 0.3333)  # Still same what a matrix
print("\nIMP1_poweronethird =\n", IMP1_poweronethird)




IMP1_poweronethird =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]


In [ ]:
# Stacking horizontally and then transposing to match MATLAB's [A B C]' logic
All_IMPs = np.hstack((IMP1, IMP2, IMP3, IMP10, IMP1_powerhalf, IMP1_poweronethird)).T

# All imps lined up identically
print("\nAll_IMPs =\n", All_IMPs)


All_IMPs =
 [[1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]
 [1.  0.  0. ]
 [0.  0.5 0.5]
 [0.  0.5 0.5]]
